spring.application.name=climalert
weather.api.url=https://api.weatherapi.com/v1
weather.api.key=${WEATHER_API_KEY}
weather.api.location=Buenos Aires
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=climalert.disenio@gmail.com
spring.mail.password=seuj vxnh vcdm jamo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true