spring.application.name=climalert
weather.api.url=https://api.weatherapi.com/v1
weather.api.key=${WEATHER_API_KEY}
weather.api.location=CABA
spring.mail.username=climalert.disenio@gmail.com
spring.mail.password=Disenio26
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true